import {chromium} from 'playwright';
import {preview} from 'vite';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {encode} from '../src/saves.ts';
import {enemyFor} from '../src/engine.ts';
import {maxHP} from '../src/progression.ts';
import {newGame} from './intake-helper.mjs';
const server=process.env.PLAYTEST_URL?null:await preview({preview:{host:'127.0.0.1',port:4192,strictPort:true}});
const url=process.env.PLAYTEST_URL||'http://127.0.0.1:4192/';
const out=new URL('../evidence/clinic-stack/',import.meta.url);await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:3440,height:1440}});const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))errors.push(r.status()+' '+r.url())});
const input=page.getByRole('textbox',{name:'Command',exact:true});
const shot=async name=>page.screenshot({path:new URL(name+'.png',out).pathname,fullPage:true});
async function cmd(text){await input.fill(text);await input.press('Enter');await page.waitForFunction(()=>!document.querySelector('.command-hint').textContent.includes('SAVING…'))}
async function state(){return page.evaluate(async()=>{const db=await new Promise(resolve=>{const r=indexedDB.open('deadlease-v2',1);r.onsuccess=()=>resolve(r.result)});try{return await new Promise(resolve=>{const r=db.transaction('slots').objectStore('slots').get('auto');r.onsuccess=()=>resolve(r.result?JSON.parse(r.result):null)})}finally{db.close()}})}
try{
 await page.goto(url);await page.getByRole('button',{name:'New game',exact:true}).waitFor();await page.waitForFunction(()=>document.activeElement?.textContent==='New game');
 await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Load game');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');
 await page.getByRole('dialog',{name:'You wake.',exact:true}).waitFor();assert(await page.getByRole('heading',{name:'Reclamation Clinic',exact:true}).isVisible());assert.equal(await page.locator('.registration,.masthead').count(),0);assert.equal(await state(),null);await shot('3440-backstory');
 await page.keyboard.press('Escape');assert(await input.evaluate(e=>e===document.activeElement));await input.press('Tab');assert.equal(await page.locator('.minimap-dialog').count(),0,'Map unavailable before registration');await cmd('talk clerk');await page.getByLabel('Name',{exact:true}).waitFor();await page.getByLabel('Name',{exact:true}).focus();await page.keyboard.insertText('Rhea');await page.waitForFunction(()=>document.querySelector('.clinic-dialog input')?.getAttribute('value')==='Rhea');await page.keyboard.press('Control+Enter');await page.getByLabel('Class',{exact:true}).waitFor();
 await page.getByLabel('Class',{exact:true}).focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');assert.equal(await page.getByLabel('Class',{exact:true}).inputValue(),'Street Medic');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.closest('label').textContent.startsWith('Bonus skill')),true);await page.keyboard.press('Home');for(let i=0;i<3;i++)await page.keyboard.press('ArrowDown');assert.equal(await page.getByLabel('Bonus skill',{exact:true}).inputValue(),'Medicine');await shot('3440-intake');
 await page.keyboard.press('Escape');assert.equal(await state(),null);await cmd('talk clerk');assert.equal(await page.getByLabel('Class',{exact:true}).inputValue(),'Street Medic');await page.keyboard.press('Control+Enter');await page.waitForFunction(()=>!document.querySelector('.clinic-dialog'));await page.waitForFunction(()=>!document.querySelector('.command-hint').textContent.includes('SAVING…'));
 const registered=await state();assert.equal(registered.player.name,'Rhea');assert.equal(registered.player.className,'Street Medic');assert.equal(registered.player.skills.Medicine,3);assert(await page.locator('.player-card').innerText().then(t=>t.includes('Rhea')&&t.includes('Street Medic')));assert.equal(await page.evaluate(()=>getComputedStyle(document.body).cursor),'none');
 const room=await page.locator('.room-panel').boundingBox(),player=await page.locator('.player-card').boundingBox(),log=await page.locator('.terminal').boundingBox();assert(room.y+room.height<=player.y);assert(player.y+player.height<=log.y);assert(player.height<room.height/3);assert(log.y+log.height<=1440);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.scene-painting img').evaluate(i=>i.decode());await shot('3440-world');checks.push('Keyboard-only title, immediate clinic, dismissible backstory, two-stage intake, draft cancellation, live character update, compact three-part ultrawide stack');
 const beforeMap=await state();await input.press('Tab');assert(await page.locator('.minimap-dialog').isVisible());await page.keyboard.type('south');await page.keyboard.press('Enter');assert.deepEqual(await state(),beforeMap);await page.keyboard.press('Tab');assert.equal(await page.locator('.minimap-dialog').count(),0);assert(await input.evaluate(e=>e===document.activeElement));await cmd('map world');assert(await page.getByRole('button',{name:'Whole estuary',exact:true}).getAttribute('aria-pressed')==='true');await page.keyboard.press('b');await page.getByRole('button',{name:'Sewers',exact:true}).and(page.locator('[aria-pressed="true"]')).waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.minimap-dialog').count(),0);await cmd('view');assert(await page.getByRole('dialog',{name:'Reclamation Clinic',exact:true}).isVisible());await page.keyboard.press('Escape');checks.push('Typed map controls and artwork, Escape closes reference panels, pointer hidden');
 const fatal=structuredClone(registered);fatal.room='alley';fatal.previous='steps';fatal.discovered.push('steps','alley');fatal.encounter=enemyFor('alley');fatal.encounter.phase=2;fatal.player.hp=1;
 await page.getByLabel('Import save file').setInputFiles({name:'fatal.json',mimeType:'application/json',buffer:Buffer.from(encode(fatal))});await page.getByRole('heading',{name:'Scrap Alley',exact:true}).waitFor();await cmd('brace');await page.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();await shot('3440-death');
 const ended=await state();assert.equal(ended.room,'alley');assert.equal(ended.player.hp,0);assert.equal(ended.run.status,'dead');assert.equal(ended.player.debt,0);assert.equal(ended.player.name,'Rhea');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Run record',exact:true}).waitFor();
 await page.reload();await page.getByRole('button',{name:'Run record',exact:true}).press('Enter');await page.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();assert.deepEqual(await state(),ended);await page.keyboard.press('Escape');await newGame(page,'Nell');await page.waitForFunction(()=>!document.querySelector('.command-hint').textContent.includes('SAVING…'));const fresh=await state();assert.equal(fresh.player.name,'Nell');assert.equal(fresh.turns,0);assert.equal(fresh.room,'clinic');assert.equal(fresh.player.hp,maxHP(fresh.player));assert.notEqual(fresh.run.id,ended.run.id);assert.deepEqual(fresh.rewards,[]);await cmd('s');await page.getByRole('heading',{name:'Clinic Steps',exact:true}).waitFor();checks.push('Terminal death record survives reload; fresh patient receives new identity, seed, pack and progress');
 for(const [width,height] of [[1280,800],[390,844]]){await page.setViewportSize({width,height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(width+'-world')}
 assert.deepEqual(errors,[]);await fs.writeFile(new URL('verification.json',out),JSON.stringify({passed:true,url,checks,errors},null,2));console.log(JSON.stringify({passed:true,url,checks,errors},null,2));
}finally{await browser.close();if(server)await new Promise(resolve=>server.httpServer.close(resolve))}
