import {chromium} from 'playwright';
import {preview} from 'vite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createGame,command} from '../src/engine.ts';
import {encode} from '../src/saves.ts';
import {gainXP} from '../src/progression.ts';
import {reconcilePack} from '../src/backpack.ts';
const out=new URL('../evidence/theft-pass/',import.meta.url);await fs.mkdir(out,{recursive:true});
const server=await preview({preview:{host:'127.0.0.1',port:4197,strictPort:true}}),browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:3440,height:1440},reducedMotion:'reduce'}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
const input=page.getByRole('textbox',{name:'Command',exact:true});
async function settled(){await page.waitForFunction(()=>!document.querySelector('.command-hint')?.textContent.includes('SAVING…')&&document.querySelector('.room-panel')?.getAttribute('aria-busy')==='false')}
async function state(){return page.evaluate(async()=>{const db=await new Promise(resolve=>{const r=indexedDB.open('deadlease-v2',1);r.onsuccess=()=>resolve(r.result)});try{return await new Promise(resolve=>{const r=db.transaction('slots').objectStore('slots').get('auto');r.onsuccess=()=>resolve(JSON.parse(r.result))})}finally{db.close()}})}
async function cmd(text){await input.fill(text);await input.press('Enter');await settled()}
async function load(g){await page.getByLabel('Import save file').setInputFiles({name:'theft-test.json',mimeType:'application/json',buffer:Buffer.from(encode(g))});await page.getByRole('heading',{name:g.room==='kiosk'?'Ration Kiosk':g.room==='yard'?'Freight Yard':'Bellwether Post',exact:true}).waitFor();await settled()}
async function shot(name){await page.locator('.room-panel img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await page.screenshot({path:new URL(name+'.png',out).pathname,fullPage:true})}
function at(room,seed=1){const g=createGame('Rhea','Baseline','Enforcer','Tech',seed,crypto.randomUUID());g.room=room;g.previous=room==='kiosk'?'clinic':room==='yard'?'relay':room;g.discovered=[...new Set(['clinic',g.previous,room])];return g}
try{
 await page.goto('http://127.0.0.1:4197/');await page.getByRole('button',{name:'New game',exact:true}).waitFor();
 await load(at('kiosk'));const before=await state();assert((await page.locator('.room-body').innerText()).includes('sealed medical kit'));assert(!(await page.getByLabel('Available commands').innerText()).includes('kit'));
 await input.fill('steal');await input.press('Control+Space');assert.equal(await input.inputValue(),'steal');await cmd('look at the kit');assert.deepEqual(await state(),before);await shot('3440-kit-prose');
 await cmd('grab the kit');assert.equal((await state()).player.inventory['medical supplies'],before.player.inventory['medical supplies']+3);assert((await page.locator('.room-body').innerText()).includes('empty rectangle'));assert.equal(await page.locator('.encounter').count(),0);
 await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).press('Enter');await settled();const stolen=await state();await cmd('grab kit');assert.deepEqual(await state(),stolen);checks.push('Room prose exposes kit; no theft hint/completion; reading is free; successful theft changes prose and cannot duplicate after reload');
 let seed=10000;while(!command(at('kiosk',seed),'steal kit').state.encounter)seed+=1000;
 await load(at('kiosk',seed));await cmd('steal kit');let caught=await state();assert.equal(caught.encounter.id,'theft:kiosk-medical-kit');assert((await page.locator('.district-bar').innerText()).includes('ENCOUNTER ACTIVE'));assert(!(await page.locator('.room-title .pill').innerText()).includes('SAFE'));assert.equal(await page.getByLabel('Available commands').count(),0);await shot('3440-caught');
 await cmd('rest');assert.deepEqual(await state(),caught);await cmd('buy medical supplies');assert.deepEqual(await state(),caught);await input.press('Tab');assert.equal(await page.locator('.minimap-dialog').count(),0);
 await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).press('Enter');await settled();assert.deepEqual(await state(),caught);await input.press('Escape');await page.locator('.pause-menu').waitFor();await page.keyboard.press('Escape');assert.deepEqual(await state(),caught);
 await cmd('flee');assert.equal((await state()).room,'clinic');await cmd('e');assert.equal((await state()).encounter.id,'theft:kiosk-medical-kit');checks.push('Caught theft creates and saves an armed encounter in a refuge; no safe badge/rest/shop/map bypass; reload/pause preserve it and returning after flight restores hostility');
 await load(at('yard'));assert((await page.locator('.room-body').innerText()).includes('immediate killing burst'));await shot('3440-watch-gun');await cmd('grab gun');await page.locator('.death-screen').waitFor();await settled();const dead=await state();assert.equal(dead.room,'yard');assert.equal(dead.run.status,'dead');assert.equal(dead.player.debt,0);assert.equal(dead.player.inventory['coil carbine'],undefined);assert(dead.rewards.includes('alarm:yard-watch-gun'));await shot('3440-gun-death');await page.keyboard.press('Escape');checks.push('Explicit prose warning precedes a lethal fresh-character gun grab; no gun reward on death, alarm retained, existing death presentation invoked');
 const veteran=at('yard');gainXP(veteran.player,10000);Object.assign(veteran.player.inventory,{'medical supplies':15,'expedition frame':1,'storm harness':1,'riot carbine':1});veteran.player.pack.bag='expedition frame';veteran.player.armor='storm harness';veteran.player.weapon='riot carbine';reconcilePack(veteran.player);await load(veteran);await cmd('grab gun');assert.equal((await state()).encounter.level,8);await shot('3440-watch-fight');
 for(let n=0;n<40;n++){const g=await state();if(!g.encounter)break;await cmd(g.encounter.phase===2?'brace':g.player.hp<50?'heal':'attack')}
 assert.equal((await state()).encounter,null);assert((await state()).rewards.includes('subdued:yard-watch-gun'));await cmd('grab gun from the table');assert.equal((await state()).player.inventory['coil carbine'],1);assert((await page.locator('.room-body').innerText()).includes('oil-dark outline'));await shot('3440-watch-cleared');
 const claimed=await state();await cmd('grab gun');assert.deepEqual(await state(),claimed);await cmd('w');await cmd('e');assert.equal((await state()).encounter,null);checks.push('An equipped veteran can defeat the fixed watch, earn the carbine once, and return without respawning or duplicating guard rewards');
 await load(at('bellwether-1'));await cmd('inspect coat');assert((await page.locator('.log').innerText()).includes('copper lining'));await shot('3440-coat-prose');await cmd('steal coat');assert.equal((await state()).player.inventory['insulated coat'],1);assert((await page.locator('.room-body').innerText()).includes('hook behind Ada’s table is bare'));
 for(const [width,height] of [[1280,800],[390,844]]){await page.setViewportSize({width,height});await load(at('yard'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(width+'-watch-prose');await load(veteran);await cmd('grab gun');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===1280){assert(await page.locator('.enemy-title').evaluate(el=>{const e=el.getBoundingClientRect(),r=el.closest('.room-panel').getBoundingClientRect();return e.bottom<=r.bottom}),'Combat portrait and intent fit without scrolling')}await shot(width+'-watch-fight')}
 checks.push('Bellwether coat can be inspected/stolen; updated prose and combat views fit ultrawide, desktop and mobile');assert.deepEqual(errors,[]);await fs.writeFile(new URL('verification.json',out),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}finally{await browser.close();await new Promise(resolve=>server.httpServer.close(resolve))}
