import {chromium} from 'playwright';
import {preview} from 'vite';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createGame,enemyFor} from '../src/engine.ts';
import {rooms} from '../src/world.ts';
import {gainXP,maxHP} from '../src/progression.ts';
import {reconcilePack} from '../src/backpack.ts';
import {encode} from '../src/saves.ts';
import {newGame} from './intake-helper.mjs';
const out=new URL('../evidence/run-pass/',import.meta.url);await fs.mkdir(out,{recursive:true});
const fixtures=new URL('../design/playtest-saves/',import.meta.url);await fs.mkdir(fixtures,{recursive:true});
const server=await preview({preview:{host:'127.0.0.1',port:4199,strictPort:true}}),browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:3440,height:1440},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],checks=[];
const url='http://127.0.0.1:4199/';
function monitor(p){p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())})}monitor(page);
async function stored(p=page,slot='auto'){return p.evaluate(async slot=>{const db=await new Promise(resolve=>{const r=indexedDB.open('deadlease-v2',1);r.onsuccess=()=>resolve(r.result)});try{return await new Promise(resolve=>{const r=db.transaction('slots').objectStore('slots').get(slot);r.onsuccess=()=>resolve(r.result?JSON.parse(r.result):null)})}finally{db.close()}},slot)}
async function settled(p=page){await p.waitForFunction(()=>!document.querySelector('.command-hint')?.textContent.includes('SAVING…')&&document.querySelector('.room-panel')?.getAttribute('aria-busy')==='false')}
async function cmd(text,p=page){const input=p.getByRole('textbox',{name:'Command',exact:true});await input.fill(text);await input.press('Enter');await settled(p)}
async function load(g,p=page){await p.getByLabel('Import save file').setInputFiles({name:'run-test.json',mimeType:'application/json',buffer:Buffer.from(encode(g))});await p.waitForFunction(id=>document.querySelector('.notice')?.textContent==='Imported valid save into manual slot and loaded it.',g.run.id);await settled(p);assert.equal((await stored(p)).run.id,g.run.id)}
function fight(name='scrap weasel',veteran=false){const r=Object.values(rooms).find(r=>r.enemy===name);const g=createGame('Test Patient','Baseline','Enforcer','Tech',1,crypto.randomUUID());if(veteran)gainXP(g.player,2700);g.room=g.previous=r.id;g.discovered=[...new Set(['clinic',r.id])];g.encounter=enemyFor(r.id);return g}
function fatal(drones=0,packed=true){const g=fight();g.player.hp=1;g.encounter.phase=2;if(drones){g.player.inventory['stitch drone']=drones;if(packed)reconcilePack(g.player)}return g}
async function shot(name){await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));await page.screenshot({path:new URL(name+'.png',out).pathname,fullPage:!(await page.locator('dialog[open]').count())})}
async function closeDeath(p=page){await p.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();await p.keyboard.press('Escape');await p.getByRole('button',{name:'Return to clinic',exact:true}).waitFor()}
try{
 await page.goto(url);await page.getByRole('button',{name:'New game',exact:true}).waitFor();
 const lethal=fatal();await load(lethal);await cmd('save');const sibling=await context.newPage();monitor(sibling);await sibling.goto(url);await sibling.getByRole('button',{name:'Continue',exact:true}).press('Enter');await settled(sibling);
 await cmd('brace');await page.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();const dead=await stored();assert.equal(dead.run.status,'dead');assert.equal(dead.player.hp,0);assert.equal(dead.room,lethal.room);assert.deepEqual(await stored(page,'ended:'+dead.run.id),dead);
 await sibling.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();assert.equal((await stored(sibling)).run.status,'dead');await sibling.close();
 for(const [w,h] of [[3440,1440],[1280,800],[390,844]]){await page.setViewportSize({width:w,height:h});assert(await page.locator('.run-end').evaluate(e=>e.scrollWidth<=e.clientWidth));await shot(w+'-run-end')}
 await page.setViewportSize({width:3440,height:1440});await page.reload();await page.getByRole('button',{name:'Return to clinic',exact:true}).press('Enter');await page.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();await closeDeath();
 await page.getByLabel('Import save file').setInputFiles({name:'old-life.json',mimeType:'application/json',buffer:Buffer.from(encode(lethal))});await page.getByRole('status').filter({hasText:'This run has ended'}).waitFor();assert.equal((await stored()).run.status,'dead');
 checks.push('Death atomically stores an immutable ended record; a second open tab follows it; reload shows Return to clinic; living import cannot resurrect it; death layouts fit all three sizes');
 await page.getByRole('button',{name:'Motion: on',exact:true}).press('Enter');await newGame(page,'Next Patient');await settled();let g=await stored();assert.notEqual(g.run.id,dead.run.id);assert.notEqual(g.run.seed,dead.run.seed);assert.equal(g.turns,0);assert.equal(g.room,'clinic');assert.deepEqual(g.rewards,[]);assert.equal(g.player.inventory['stitch drone'],undefined);assert.equal((await stored(page,'preferences')).motion,false);assert.deepEqual(await stored(page,'ended:'+dead.run.id),dead);checks.push('New clinic intake produces a new seed/identity and clean progress, preserves preferences and the prior ended record');
 const storageFailure=fatal();await load(storageFailure);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;let once=true;IDBObjectStore.prototype.put=function(value,key){if(once&&key==='auto'){once=false;throw new DOMException('Simulated storage full','QuotaExceededError')}return put.call(this,value,key)}});await cmd('brace');await page.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();assert(await page.getByRole('button',{name:'Wake at clinic',exact:true}).isDisabled());assert.equal((await stored()).run.status,'alive');await page.getByRole('button',{name:'Retry saving record',exact:true}).press('Enter');await page.getByRole('button',{name:'Wake at clinic',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.run-end button.primary')?.disabled);assert.equal((await stored()).run.status,'dead');assert.equal((await stored(page,'ended:'+storageFailure.run.id)).run.status,'dead');await closeDeath();checks.push('An aborted death transaction blocks reconstruction; explicit retry preserves previous bytes and saves the terminal record before enabling recovery');
 const rescued=fatal(2);await load(rescued);await cmd('inventory');await page.locator('.inventory-dialog').waitFor();await page.locator('img[src$="stitch-drone.png"]').first().evaluate(i=>i.decode());await shot('3440-drone-pack');await page.keyboard.press('Escape');await cmd('brace');g=await stored();assert.equal(g.run.revivals,1);assert.equal(g.player.inventory['stitch drone'],1);assert.equal(g.player.hp,Math.ceil(maxHP(g.player)/2));assert.equal(g.room,rescued.room);assert.equal(g.encounter.hp,rescued.encounter.hp);await shot('3440-drone-rescue');await page.reload();await page.getByRole('button',{name:'Continue',exact:true}).press('Enter');await settled();assert.deepEqual(await stored(),g);g.player.hp=1;g.encounter.phase=2;await load(g);await cmd('brace');g=await stored();assert.equal(g.run.revivals,2);assert.equal(g.player.inventory['stitch drone'],undefined);checks.push('Two packed drones rescue on separate lethal actions; each is consumed exactly once; current encounter and consumed state survive reload');
 const unpacked=fatal(1,false);await load(unpacked);await cmd('brace');assert.equal((await stored()).run.status,'dead');assert.equal((await stored()).player.inventory['stitch drone'],1);await closeDeath();checks.push('An owned but unpacked drone cannot prevent death');
 const bleed=fatal(2);bleed.bleed=3;await load(bleed);await cmd('brace');g=await stored();assert.equal(g.run.revivals,1);assert.equal(g.bleed,0);assert.equal(g.encounter.phase,2);assert.equal(g.player.hp,maxHP(g.player)/2);checks.push('Bleeding rescue cancels the remaining enemy response, consuming only one drone');
 const marksman=fight('alley marksman',true);await load(marksman);assert((await page.locator('.encounter').innerText()).includes('AIMING'));await cmd('cover');assert.equal((await stored()).encounter.phase,2);assert((await page.locator('.encounter').innerText()).includes('RELOADING'));await shot('3440-marksman');await cmd('brace');assert.equal((await stored()).player.hp,marksman.player.hp);checks.push('Marksman cover breaks aim and produces a harmless reload, with readable intent');
 const knife=fight('street cutthroat',true);await load(knife);await cmd('dance');g=await stored();assert.equal(g.bleed,3);assert((await page.locator('.log').innerText()).includes('BLEED'));await cmd('look');assert.deepEqual(await stored(),g);await cmd('pause');await page.locator('.pause-menu').waitFor();await page.waitForTimeout(1100);assert.deepEqual(await stored(),g);await page.keyboard.press('Escape');await cmd('heal');assert.equal((await stored()).bleed,0);checks.push('Knife bleeding is visible, free look and pause do not tick it, and medical supplies stop it');
 const brute=fight('tread brute',true);await load(brute);for(let n=0;n<3;n++)await cmd('brace');g=await stored();assert.equal(g.encounter.heat,3);assert((await page.locator('.encounter').innerText()).includes('OVERHEATED'));await shot('3440-overheat');for(let n=0;n<3;n++)await cmd('brace');assert.equal((await stored()).player.hp,g.player.hp);assert.equal((await stored()).encounter.phase,0);checks.push('Tread brute heat creates three harmless cooling responses before restarting its attack cycle');
 const surrendered=fight('street cutthroat',true);surrendered.encounter.hp=Math.floor(surrendered.encounter.maxHP*.2);await load(surrendered);await cmd('brace');g=await stored();assert.equal(g.encounter.morale,'surrendered');await shot('3440-surrender');await cmd('spare');g=await stored();assert.equal(g.encounter,null);assert.equal(g.run.kills,0);assert(g.player.credits>surrendered.player.credits);await cmd('spare');assert.deepEqual(await stored(),g);checks.push('A surrendered human can be spared with one partial payout, no kill credit and no duplicate claim');
 // A stale tab that never receives the polling notification still cannot overwrite a sealed run.
 const staleContext=await browser.newContext();await staleContext.addInitScript(()=>{window.setInterval=()=>0});const stale=await staleContext.newPage();monitor(stale);await stale.goto(url);await stale.getByRole('button',{name:'New game',exact:true}).waitFor();const race=fatal();await load(race,stale);await stale.reload();await stale.getByRole('button',{name:'Continue',exact:true}).press('Enter');const killer=await staleContext.newPage();monitor(killer);await killer.goto(url);await killer.getByRole('button',{name:'Continue',exact:true}).press('Enter');await settled(killer);await cmd('brace',killer);await cmd('heal',stale);await stale.getByRole('status').filter({hasText:'This run has ended'}).waitFor();assert.equal((await stored(stale)).run.status,'dead');await staleContext.close();checks.push('A stale tab without polling cannot overwrite a death seal with its living branch');
 for(const [name,state] of [['01-packed-drone',fatal(2)],['02-unpacked-drone',fatal(1,false)],['03-marksman',fight('alley marksman',true)],['04-cutthroat',fight('street cutthroat',true)],['05-tread-brute',fight('tread brute',true)],['06-surrender',surrendered]]){state.run.id='playtest-'+name;await fs.writeFile(new URL(name+'.json',fixtures),encode(state)+'\n')}
 assert.deepEqual(errors,[]);await fs.writeFile(new URL('verification.json',out),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}finally{await browser.close();await new Promise(resolve=>server.httpServer.close(resolve))}
