import {chromium} from 'playwright';
import {preview} from 'vite';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {newGame} from './intake-helper.mjs';
import {createGame,enemyFor} from '../src/engine.ts';
import {encode} from '../src/saves.ts';
const out=new URL('../evidence/motion-pass/',import.meta.url);await fs.mkdir(out,{recursive:true});
const server=await preview({preview:{host:'127.0.0.1',port:4194,strictPort:true}}),browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:3440,height:1440},recordVideo:{dir:new URL('recordings/',out).pathname,size:{width:1280,height:536}}}),page=await context.newPage(),checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
await page.addInitScript(()=>{
 window.__impacts=[];window.__audio=[];
 const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){window.__impacts.push({target:this.className,delay:options.delay,duration:options.duration,at:performance.now()});return animate.call(this,frames,options)};
 const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){window.__audio.push({src:this.src,at:performance.now()});return play.call(this)};
});
const input=page.getByRole('textbox',{name:'Command',exact:true});
async function stored(slot='auto'){return page.evaluate(async slot=>{const db=await new Promise(resolve=>{const r=indexedDB.open('deadlease-v2',1);r.onsuccess=()=>resolve(r.result)});try{return await new Promise(resolve=>{const r=db.transaction('slots').objectStore('slots').get(slot);r.onsuccess=()=>resolve(r.result)})}finally{db.close()}},slot)}
async function settled(){await page.waitForFunction(()=>!!document.querySelector('.title-screen')||document.querySelector('.room-panel')?.getAttribute('aria-busy')==='false'&&!document.querySelector('.command-hint')?.textContent.includes('SAVING…'))}
async function cmd(text){const before=await page.locator('.log').textContent();await input.fill(text);await input.press('Enter');if(await page.locator('.timing-strike[open]').count())await page.keyboard.press('Enter');await page.waitForFunction(before=>document.querySelector('.log')?.textContent!==before,before);await settled()}
async function importGame(g){await page.getByLabel('Import save file').setInputFiles({name:'motion-test.json',mimeType:'application/json',buffer:Buffer.from(encode(g))});for(let n=0;n<100&&await stored()!==encode(g);n++)await page.waitForTimeout(30);assert.equal(await stored(),encode(g));await settled()}
async function shot(name){await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));await page.screenshot({path:new URL(name+'.png',out).pathname});}
try{
 await page.goto('http://127.0.0.1:4194/');await page.waitForFunction(()=>document.activeElement?.textContent==='New game');await page.locator('.title-art').evaluate(i=>i.decode());
 assert(await page.locator('.title-art').evaluate(e=>e.getAnimations().some(a=>a.playState==='running')));await page.locator('.title-menu h1').evaluate(e=>Promise.all(e.getAnimations().map(a=>a.finished)));await shot('3440-title');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForFunction(()=>document.querySelector('.app').dataset.pageHidden==='true');assert.equal(await page.locator('.title-art').evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))});
 await page.getByRole('button',{name:'Motion: on',exact:true}).press('Enter');assert.equal(await page.locator('.title-art').evaluate(e=>getComputedStyle(e).animationName),'none');for(let n=0;n<100&&JSON.parse(await stored('preferences')??'{}').motion!==false;n++)await page.waitForTimeout(20);assert.equal(JSON.parse(await stored('preferences')).motion,false);await page.reload();await page.getByRole('button',{name:'Motion: off',exact:true}).waitFor();await page.getByRole('button',{name:'Motion: off',exact:true}).press('Enter');checks.push('Animated title, keyboard menu immediately available, persistent motion toggle, hidden-page pause');
 await newGame(page,'Rhea');await settled();const terminal=await input.boundingBox();
 await cmd('s');assert.equal(await page.locator('.room-panel').getAttribute('data-travel-direction'),'south');assert.deepEqual(await input.boundingBox(),terminal);
 await cmd('down');assert.equal(await page.locator('.room-panel').getAttribute('data-travel-direction'),'down');await cmd('up');assert.equal(await page.locator('.room-panel').getAttribute('data-travel-direction'),'up');checks.push('Directional walking and ladder transitions; command line stays in place');
 const g=createGame('Rhea');g.room='alley';g.previous='steps';g.discovered.push('steps','alley');g.encounter=enemyFor('alley');g.encounter.phase=2;g.rng=1;
 await importGame(g);await page.evaluate(()=>{window.__impacts=[];window.__audio=[]});await cmd('attack');await page.waitForFunction(()=>window.__impacts.length===2);const impacts=await page.evaluate(()=>window.__impacts);assert(impacts.some(e=>e.target.includes('enemy-painting')&&e.delay===140));assert(impacts.some(e=>e.target==='resource'&&e.delay===520));
 await page.waitForFunction(()=>window.__audio.filter(e=>e.src.endsWith('attack-impact.wav')).length===2);const impactAudio=await page.evaluate(()=>window.__audio.filter(e=>e.src.endsWith('attack-impact.wav')));for(let n=0;n<2;n++)assert(Math.abs(impactAudio[n].at-(impacts[n].at+impacts[n].delay))<100,'Visual and audio impacts start together');await shot('3440-combat');checks.push('Enemy and player art receive separate 210 ms hit reactions at matching audio offsets');
 const before=await stored();await cmd('settings');await page.getByLabel('Atmospheric motion (respects reduced motion)').uncheck();assert.equal(await stored(),before);await page.keyboard.press('Escape');assert.equal(await page.locator('.settings').isVisible(),false);await importGame(g);await page.evaluate(()=>window.__impacts=[]);await cmd('attack');await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__impacts.length),0);checks.push('Disabling motion preserves saves and suppresses impact movement');
 await cmd('settings');await page.getByLabel('Atmospheric motion (respects reduced motion)').check();await page.keyboard.press('Escape');assert.equal(await page.locator('.settings').isVisible(),false);
 await page.emulateMedia({reducedMotion:'reduce'});await importGame(createGame('Rhea'));await cmd('s');assert.equal(await page.locator('.room-panel').evaluate(e=>getComputedStyle(e).animationName),'none');await importGame(g);await page.evaluate(()=>window.__impacts=[]);await cmd('attack');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.__impacts.length),0);checks.push('OS reduced motion suppresses travel and hit motion');
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1280,height:800});await importGame(g);await page.evaluate(()=>window.__impacts=[]);await cmd('attack');await page.waitForFunction(()=>window.__impacts.length===2);assert((await page.evaluate(()=>window.__impacts)).some(e=>e.target==='resource'));await shot('1280-combat');await page.setViewportSize({width:3440,height:1440});checks.push('Compact layout uses health readout when the player portrait is hidden');g.player.hp=1;await importGame(g);await cmd('brace');await page.getByRole('dialog',{name:'Everything goes quiet.',exact:true}).waitFor();assert(await page.locator('.death-trace').evaluate(e=>e.getAnimations().length>0));await page.locator('.death-trace').evaluate(e=>Promise.all(e.getAnimations().map(a=>a.finished)));await shot('3440-death');
 for(const [width,height] of [[1280,800],[390,844]]){await page.setViewportSize({width,height});assert(await page.locator('.death-screen').evaluate(e=>e.scrollWidth<=e.clientWidth));await shot(width+'-death')}
 await page.keyboard.press('Escape');assert.equal(await page.locator('.death-screen[open]').count(),0);assert(await page.getByRole('button',{name:'Return to clinic',exact:true}).isVisible());checks.push('Full-screen one-shot death signal, compact layouts, immediate dismissal to title');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.title-art').evaluate(e=>getComputedStyle(e).animationName),'none');await shot('390-title-static');
 assert.deepEqual(errors,[]);await fs.writeFile(new URL('verification.json',out),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
}finally{await context.close();await page.video()?.saveAs(new URL('motion-playtest.webm',out).pathname);await browser.close();await new Promise(resolve=>server.httpServer.close(resolve))}
