/** All tunable numeric rules live here; content-specific ability magnitudes live in typed class data. */
export interface Balance {skillDamage:number;techRestRecovery:number;ferrymanFactor:number;ashArmor:number;sumpReduction:number;shieldCap:number;exposureDuration:number;aimCost:number;surveyorAimCost:number;coverCost:number;aimAccuracy:number;attackRecovery:number;wireRecovery:number;enforcerRecovery:number;glassAccuracy:number;enemyAccuracy:number;damageVariance:number;enemyVariance:number;radbornFactor:number;insulationFactor:number;scroungeBase:number;scroungeSkill:number;scavengerBonus:number;scroungeXP:number;salvagePrice:number;advocateDiscount:number;medicBonus:number;maxLevel:number;xpStep:number;hpBase:number;hpGrit:number;hpLevel:number;staminaBase:number;staminaGrit:number;staminaLevel:number;deathDebt:number;skillCap:number;respawnTurns:number;baseAccuracy:number;reflexAccuracy:number;skillAccuracy:number;minAccuracy:number;maxAccuracy:number;radThreshold:number;radPenalty:number;braceFlat:number;braceSpikeFactor:number;coverFactor:number;healBase:number;healMedicine:number;healWits:number;restHP:number;restStamina:number;enemyHPBase:number;enemyHPLevel:number;enemyDamageBase:number;enemyDamageLevel:number;spikeMultiplier:number;enemyXPLevel:number;enemyCreditsLevel:number;maxSaveBytes:number;maxCounter:number;maxInventory:number;logLimit:number}
export const BALANCE:Readonly<Balance>={skillDamage:2,techRestRecovery:2,ferrymanFactor:.5,ashArmor:1,sumpReduction:1,shieldCap:100,exposureDuration:4,aimCost:4,surveyorAimCost:2,coverCost:3,aimAccuracy:25,attackRecovery:2,wireRecovery:1,enforcerRecovery:2,glassAccuracy:8,enemyAccuracy:.85,damageVariance:4,enemyVariance:3,radbornFactor:.75,insulationFactor:.5,scroungeBase:6,scroungeSkill:2,scavengerBonus:4,scroungeXP:10,salvagePrice:4,advocateDiscount:2,medicBonus:4,maxLevel:10,xpStep:60,hpBase:24,hpGrit:6,hpLevel:6,staminaBase:12,staminaGrit:3,staminaLevel:2,deathDebt:25,skillCap:5,respawnTurns:12,baseAccuracy:58,reflexAccuracy:2,skillAccuracy:4,minAccuracy:10,maxAccuracy:95,radThreshold:50,radPenalty:15,braceFlat:6,braceSpikeFactor:0.5,coverFactor:0.35,healBase:18,healMedicine:3,healWits:2,restHP:18,restStamina:14,enemyHPBase:14,enemyHPLevel:10,enemyDamageBase:3,enemyDamageLevel:2,spikeMultiplier:3,enemyXPLevel:16,enemyCreditsLevel:6,maxSaveBytes:1000000,maxCounter:10000000,maxInventory:100000,logLimit:180};
export const SKILLS=['Melee','Firearms','Tech','Medicine','Survival','Influence'] as const;
export type Skill=typeof SKILLS[number];
export const STATS=['Grit','Reflex','Wits','Nerve'] as const;
export type Stat=typeof STATS[number];

export const PUMP_REWARDS:Readonly<{repairXP:number;endingXP:number;commonsCredits:number;leaseCredits:number}>={repairXP:60,endingXP:80,commonsCredits:20,leaseCredits:60};
