export interface Quest {id:string;title:string;giver:string;location:string;item:string;xp:number;credits:number;brief:string;ending:string}
export const quests:Record<string,Quest>={};
Object.assign(quests,{
 weather:{id:'weather',title:'A forecast for the missing',giver:'quay-0',location:'quay-16',item:'weather recording',xp:90,credits:45,brief:'Sera needs the sealed weather recording at Receiver Pier, around the hook of Salt Quay.',ending:'Sera plays the forecast for the families. It predicts clear skies. They ask to hear it again.'},
 filter:{id:'filter',title:'Something clean',giver:'reed-0',location:'reed-16',item:'filter core',xp:130,credits:65,brief:'Fen needs the filter core on Fen Catwalk at the southwest tip of the marsh.',ending:'Clean water trickles into the shelter basin. Fen washes the ink of a water lease off a child\'s hands.'},
 spindle:{id:'spindle',title:'The workers own the pressure',giver:'foundry-0',location:'foundry-15',item:'governor spindle',xp:180,credits:85,brief:'Rusk needs the governor spindle from Governor Cage in the northern foundry row.',ending:'Rusk quiets the pressure lines. For the first time in years the canteen workers can hear one another over supper.'},
 lens:{id:'lens',title:'An honest reflection',giver:'glass-6',location:'glass-10',item:'lens fragment',xp:230,credits:100,brief:'Vale wants the lens fragment from Refraction Well just south of the Glaziers Hearth.',ending:'The repaired lens shows the ward as it is. Vale covers the corporate mirrors and opens a window.'},
 drain:{id:'drain',title:'Below the waterline',giver:'sewer-0',location:'sewer-15',item:'drain seal',xp:120,credits:60,brief:'Hal needs the drain seal at Outfall Shrine, at the eastern end of the lower sewer channel.',ending:'Hal bolts the seal into place. The sleeping mats stay dry when the tide rises; nobody sends an invoice.'},
 ledger:{id:'ledger',title:'The last account',giver:'crown-15',location:'crown-14',item:'master ledger',xp:400,credits:160,brief:'Archivist Sen needs the master ledger from Ledger Vault, west of Crown Receiver. Then resolve erase or resolve disclose.',ending:'The receiver carries your decision across the estuary.'}
} satisfies Record<string,Quest>);
